export const STARTER_INSTALLERS = [
  {
    winget_id: "Google.Chrome",
    installer_type: "msi",
    download_url: "https://dl.google.com/chrome/install/googlechromestandaloneenterprise64.msi",
    silent_install_args: "/qn /norestart",
    silent_uninstall_args: "/qn /norestart",
  },
  {
    winget_id: "Mozilla.Firefox",
    installer_type: "exe",
    download_url: "https://download.mozilla.org/?product=firefox-latest-ssl&os=win64&lang=en-US",
    silent_install_args: "/S",
    silent_uninstall_args: "/S",
  },
  {
    winget_id: "Microsoft.Edge",
    installer_type: "msi",
    download_url: "https://go.microsoft.com/fwlink/?linkid=2093437",
    silent_install_args: "/qn /norestart",
    silent_uninstall_args: "/qn /norestart",
  },
  {
    winget_id: "Microsoft.VisualStudioCode",
    installer_type: "exe",
    download_url: "https://update.code.visualstudio.com/latest/win32-x64-user/stable",
    silent_install_args: "/VERYSILENT /MERGETASKS=!runcode",
    silent_uninstall_args: "/VERYSILENT",
  },
  {
    winget_id: "OpenJS.NodeJS.LTS",
    installer_type: "msi",
    download_url: "https://nodejs.org/dist/latest-v24.x/node-v24.16.0-x64.msi",
    silent_install_args: "/qn /norestart",
    silent_uninstall_args: "/qn /norestart",
  },
  {
    winget_id: "Git.Git",
    installer_type: "exe",
    download_url: "https://github.com/git-for-windows/git/releases/latest",
    silent_install_args: "/VERYSILENT /NORESTART",
    silent_uninstall_args: "/VERYSILENT /NORESTART",
  },
  {
    winget_id: "GitHub.GitHubDesktop",
    installer_type: "exe",
    download_url: "https://central.github.com/deployments/desktop/desktop/latest/win32",
    silent_install_args: "/silent",
    silent_uninstall_args: "/silent",
  },
  {
    winget_id: "7zip.7zip",
    installer_type: "exe",
    download_url: "https://www.7-zip.org/a/7z2601-x64.exe",
    silent_install_args: "/S",
    silent_uninstall_args: "/S",
  },
  {
    winget_id: "Notepad++.Notepad++",
    installer_type: "exe",
    download_url: "https://github.com/notepad-plus-plus/notepad-plus-plus/releases/latest",
    silent_install_args: "/S",
    silent_uninstall_args: "/S",
  },
  {
    winget_id: "ShareX.ShareX",
    installer_type: "exe",
    download_url: "https://github.com/ShareX/ShareX/releases/latest",
    silent_install_args: "/VERYSILENT /NORESTART",
    silent_uninstall_args: "/VERYSILENT /NORESTART",
  },
];