export const STARTER_INSTALLERS = [
  {
    winget_id: "Google.Chrome",
    installer_type: "msi",
    download_url: "https://dl.google.com/chrome/install/googlechromestandaloneenterprise64.msi",
    download_resolver: "direct_url",
    resolver_metadata: {},
    silent_install_args: "/qn /norestart",
    silent_uninstall_args: "/qn /norestart",
  },
  {
    winget_id: "Mozilla.Firefox",
    installer_type: "exe",
    download_url: "https://download.mozilla.org/?product=firefox-latest-ssl&os=win64&lang=en-US",
    download_resolver: "direct_url",
    resolver_metadata: {},
    silent_install_args: "/S",
    silent_uninstall_args: "/S",
  },
  {
    winget_id: "Microsoft.Edge",
    installer_type: "msi",
    download_url: "https://go.microsoft.com/fwlink/?linkid=2093437",
    download_resolver: "direct_url",
    resolver_metadata: {},
    silent_install_args: "/qn /norestart",
    silent_uninstall_args: "/qn /norestart",
  },
  {
    winget_id: "Microsoft.VisualStudioCode",
    installer_type: "exe",
    download_url: "https://update.code.visualstudio.com/latest/win32-x64-user/stable",
    download_resolver: "direct_url",
    resolver_metadata: {},
    silent_install_args: "/VERYSILENT /MERGETASKS=!runcode",
    silent_uninstall_args: "/VERYSILENT",
  },
  {
    winget_id: "OpenJS.NodeJS.LTS",
    installer_type: "msi",
    download_url: "https://nodejs.org/dist/latest-v24.x/node-v24.16.0-x64.msi",
    download_resolver: "direct_url",
    resolver_metadata: {},
    silent_install_args: "/qn /norestart",
    silent_uninstall_args: "/qn /norestart",
  },
  {
    winget_id: "Git.Git",
    installer_type: "exe",
    download_url: "https://github.com/git-for-windows/git/releases/latest",
    download_resolver: "github_asset",
    resolver_metadata: {
      owner: "git-for-windows",
      repo: "git",
      assetPattern: "Git-*-64-bit.exe",
    },
    silent_install_args: "/VERYSILENT /NORESTART",
    silent_uninstall_args: "/VERYSILENT /NORESTART",
  },
  {
    winget_id: "GitHub.GitHubDesktop",
    installer_type: "exe",
    download_url: "https://central.github.com/deployments/desktop/desktop/latest/win32",
    download_resolver: "direct_url",
    resolver_metadata: {},
    silent_install_args: "/silent",
    silent_uninstall_args: "/silent",
  },
  {
    winget_id: "7zip.7zip",
    installer_type: "exe",
    download_url: "https://www.7-zip.org/a/7z2601-x64.exe",
    download_resolver: "direct_url",
    resolver_metadata: {},
    silent_install_args: "/S",
    silent_uninstall_args: "/S",
  },
  {
    winget_id: "Notepad++.Notepad++",
    installer_type: "exe",
    download_url: "https://github.com/notepad-plus-plus/notepad-plus-plus/releases/latest",
    download_resolver: "github_asset",
    resolver_metadata: {
      owner: "notepad-plus-plus",
      repo: "notepad-plus-plus",
      assetPattern: "npp.*.Installer.x64.exe",
    },
    silent_install_args: "/S",
    silent_uninstall_args: "/S",
  },
  {
    winget_id: "ShareX.ShareX",
    installer_type: "exe",
    download_url: "https://github.com/ShareX/ShareX/releases/latest",
    download_resolver: "github_asset",
    resolver_metadata: {
      owner: "ShareX",
      repo: "ShareX",
      assetPattern: "ShareX-*-setup-x64.exe",
    },
    silent_install_args: "/VERYSILENT /NORESTART",
    silent_uninstall_args: "/VERYSILENT /NORESTART",
  },

  {
    winget_id: "Zoom.Zoom",
    installer_type: "exe",
    download_url: "https://zoom.us/client/latest/ZoomInstallerFull.exe?archType=x64",
    download_resolver: "direct_url",
    resolver_metadata: {},
    silent_install_args: "/silent",
    silent_uninstall_args: "/uninstall /silent",
  },
  {
    winget_id: "SlackTechnologies.Slack",
    installer_type: "exe",
    download_url: "https://downloads.slack-edge.com/releases/windows/latest/prod/x64",
    download_resolver: "direct_url",
    resolver_metadata: {},
    silent_install_args: "/S",
    silent_uninstall_args: "/S",
  },
  {
    winget_id: "Microsoft.Teams",
    installer_type: "exe",
    download_url: "https://go.microsoft.com/fwlink/?linkid=2196106",
    download_resolver: "direct_url",
    resolver_metadata: {},
    silent_install_args: "-p",
    silent_uninstall_args: "-x",
  },
  {
    winget_id: "VideoLAN.VLC",
    installer_type: "exe",
    download_url: "https://get.videolan.org/vlc/3.0.23/win64/vlc-3.0.23-win64.exe",
    download_resolver: "direct_url",
    resolver_metadata: {},
    silent_install_args: "/S",
    silent_uninstall_args: "/S",
  },
  {
    winget_id: "FileZilla.FileZilla",
    installer_type: "exe",
    download_url: "https://download.filezilla-project.org/client/FileZilla_latest_win64-setup.exe",
    download_resolver: "direct_url",
    resolver_metadata: {},
    silent_install_args: "/S",
    silent_uninstall_args: "/S",
  },
  {
    winget_id: "WinSCP.WinSCP",
    installer_type: "exe",
    download_url: "https://winscp.net/download/WinSCP-Setup.exe",
    download_resolver: "direct_url",
    resolver_metadata: {},
    silent_install_args: "/VERYSILENT /NORESTART",
    silent_uninstall_args: "/VERYSILENT /NORESTART",
  },
  {
    winget_id: "PuTTY.PuTTY",
    installer_type: "msi",
    download_url: "https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-installer.msi",
    download_resolver: "direct_url",
    resolver_metadata: {},
    silent_install_args: "/qn /norestart",
    silent_uninstall_args: "/qn /norestart",
  },
  {
    winget_id: "Python.Python.3.13",
    installer_type: "exe",
    download_url: "https://www.python.org/ftp/python/3.13.9/python-3.13.9-amd64.exe",
    download_resolver: "direct_url",
    resolver_metadata: {},
    silent_install_args: "/quiet InstallAllUsers=1 PrependPath=1 Include_test=0",
    silent_uninstall_args: "/quiet",
  },
  {
    winget_id: "Docker.DockerDesktop",
    installer_type: "exe",
    download_url: "https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe",
    download_resolver: "direct_url",
    resolver_metadata: {},
    silent_install_args: "install --quiet",
    silent_uninstall_args: "uninstall --quiet",
  },
  {
    winget_id: "Microsoft.PowerToys",
    installer_type: "exe",
    download_url: "https://github.com/microsoft/PowerToys/releases/latest",
    download_resolver: "github_asset",
    resolver_metadata: {
      owner: "microsoft",
      repo: "PowerToys",
      assetPattern: "PowerToysUserSetup-*-x64.exe",
    },
    silent_install_args: "/quiet /norestart",
    silent_uninstall_args: "/quiet /norestart",
  },
  {
    winget_id: "Bitwarden.Bitwarden",
    installer_type: "exe",
    download_url: "https://vault.bitwarden.com/download/?app=desktop&platform=windows",
    download_resolver: "direct_url",
    resolver_metadata: {},
    silent_install_args: "/S",
    silent_uninstall_args: "/S",
  },
  {
    winget_id: "KeePassXCTeam.KeePassXC",
    installer_type: "msi",
    download_url: "https://github.com/keepassxreboot/keepassxc/releases/latest",
    download_resolver: "github_asset",
    resolver_metadata: {
      owner: "keepassxreboot",
      repo: "keepassxc",
      assetPattern: "KeePassXC-*-Win64.msi",
    },
    silent_install_args: "/qn /norestart",
    silent_uninstall_args: "/qn /norestart",
  },
  {
    winget_id: "tailscale.tailscale",
    installer_type: "msi",
    download_url: "https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi",
    download_resolver: "direct_url",
    resolver_metadata: {},
    silent_install_args: "/quiet /norestart",
    silent_uninstall_args: "/quiet /norestart",
  },
  {
    winget_id: "RustDesk.RustDesk",
    installer_type: "exe",
    download_url: "https://github.com/rustdesk/rustdesk/releases/latest",
    download_resolver: "github_asset",
    resolver_metadata: {
      owner: "rustdesk",
      repo: "rustdesk",
      assetPattern: "rustdesk-*-x86_64.exe",
    },
    silent_install_args: "--silent-install",
    silent_uninstall_args: "--silent-uninstall",
  },
  {
    winget_id: "TheDocumentFoundation.LibreOffice",
    installer_type: "msi",
    download_url: "https://download.documentfoundation.org/libreoffice/stable/26.2.4/win/x86_64/LibreOffice_26.2.4_Win_x86-64.msi",
    download_resolver: "direct_url",
    resolver_metadata: {},
    silent_install_args: "/qn /norestart",
    silent_uninstall_args: "/qn /norestart",
  },
];