export const STARTER_SOURCES = [
  {
    name: "Google Chrome",
    vendor: "Google",
    winget_id: "Google.Chrome",
    category: "Browser",
    homepage_url: "https://www.google.com/chrome/",
    source_name: "Google Chrome VersionHistory API",
    source_type: "vendor_json",
    metadata: {
      url: "https://versionhistory.googleapis.com/v1/chrome/platforms/win/channels/stable/versions",
      arrayPath: "versions",
      arrayIndex: 0,
      versionPath: "version",
      releaseUrl: "https://chromereleases.googleblog.com/",
    },
  },
  {
    name: "Mozilla Firefox",
    vendor: "Mozilla",
    winget_id: "Mozilla.Firefox",
    category: "Browser",
    homepage_url: "https://www.mozilla.org/firefox/",
    source_name: "Mozilla Product Details",
    source_type: "vendor_json",
    metadata: {
      url: "https://product-details.mozilla.org/1.0/firefox_versions.json",
      versionPath: "LATEST_FIREFOX_VERSION",
      releaseUrl: "https://www.mozilla.org/firefox/releases/",
    },
  },
  {
    name: "Microsoft Edge",
    vendor: "Microsoft",
    winget_id: "Microsoft.Edge",
    category: "Browser",
    homepage_url: "https://www.microsoft.com/edge",
    source_name: "Microsoft Edge Update API",
    source_type: "vendor_json",
    metadata: {
      url: "https://edgeupdates.microsoft.com/api/products",
      arrayFind: {
        product: "Stable",
        platform: "Windows",
        architecture: "x64"
      },
      versionPath: "releases.0.product_version",
      releaseUrl: "https://learn.microsoft.com/deployedge/microsoft-edge-relnote-stable-channel",
    },
  },
  {
    name: "Visual Studio Code",
    vendor: "Microsoft",
    winget_id: "Microsoft.VisualStudioCode",
    category: "Developer Tool",
    homepage_url: "https://code.visualstudio.com/",
    source_name: "VS Code Stable API",
    source_type: "vendor_json",
    metadata: {
      url: "https://update.code.visualstudio.com/api/releases/stable",
      arrayIndex: 0,
      releaseUrl: "https://code.visualstudio.com/updates",
    },
  },
  {
    name: "Node.js LTS",
    vendor: "OpenJS Foundation",
    winget_id: "OpenJS.NodeJS.LTS",
    category: "Runtime",
    homepage_url: "https://nodejs.org/",
    source_name: "Node.js Release Index",
    source_type: "vendor_json",
    metadata: {
      url: "https://nodejs.org/dist/index.json",
      arrayFind: {
      lts: true
    },
fallbackArrayIndex: 0,
      versionPath: "version",
      stripPrefix: "v",
      releaseUrl: "https://nodejs.org/en/about/previous-releases",
    },
  },
  {
    name: "Git for Windows",
    vendor: "Git",
    winget_id: "Git.Git",
    category: "Developer Tool",
    homepage_url: "https://gitforwindows.org/",
    source_name: "GitHub Releases",
    source_type: "github_release",
    metadata: {
      owner: "git-for-windows",
      repo: "git",
    },
  },
  {
    name: "GitHub Desktop",
    vendor: "GitHub",
    winget_id: "GitHub.GitHubDesktop",
    category: "Developer Tool",
    homepage_url: "https://desktop.github.com/",
    source_name: "GitHub Releases",
    source_type: "github_release",
    metadata: {
      owner: "desktop",
      repo: "desktop",
    },
  },
  {
    name: "7-Zip",
    vendor: "Igor Pavlov",
    winget_id: "7zip.7zip",
    category: "Compression",
    homepage_url: "https://www.7-zip.org/",
    source_name: "7-Zip Download Page",
    source_type: "vendor_html",
    metadata: {
      url: "https://www.7-zip.org/download.html",
      versionPattern: "Download 7-Zip ([0-9.]+)",
      releaseUrl: "https://www.7-zip.org/download.html",
    },
  },
  {
    name: "Notepad++",
    vendor: "Notepad++",
    winget_id: "Notepad++.Notepad++",
    category: "Editor",
    homepage_url: "https://notepad-plus-plus.org/",
    source_name: "GitHub Releases",
    source_type: "github_release",
    metadata: {
      owner: "notepad-plus-plus",
      repo: "notepad-plus-plus",
    },
  },
  {
    name: "ShareX",
    vendor: "ShareX",
    winget_id: "ShareX.ShareX",
    category: "Utility",
    homepage_url: "https://getsharex.com/",
    source_name: "GitHub Releases",
    source_type: "github_release",
    metadata: {
      owner: "ShareX",
      repo: "ShareX",
    },
  },
];