export const STARTER_SOURCES = [
  {
    name: "Google Chrome",
    vendor: "Google",
    winget_id: "Google.Chrome",
    category: "Browser",
    homepage_url: "https://www.google.com/chrome/",
    source_name: "Google Chrome VersionHistory API",
    source_type: "vendor_json",
    metadata: {
      url: "https://versionhistory.googleapis.com/v1/chrome/platforms/win/channels/stable/versions?order_by=version%20desc&page_size=1",
      arrayPath: "versions",
      arrayIndex: 0,
      versionPath: "version",
      releaseUrl: "https://chromereleases.googleblog.com/",
      downloadUrl: "https://www.google.com/chrome/",
    },
  },
  {
    name: "Mozilla Firefox",
    vendor: "Mozilla",
    winget_id: "Mozilla.Firefox",
    category: "Browser",
    homepage_url: "https://www.mozilla.org/firefox/",
    source_name: "Mozilla Product Details",
    source_type: "vendor_json",
    metadata: {
      url: "https://product-details.mozilla.org/1.0/firefox_versions.json",
      versionPath: "LATEST_FIREFOX_VERSION",
      releaseUrl: "https://www.mozilla.org/firefox/releases/",
      downloadUrl: "https://www.mozilla.org/firefox/all/",
    },
  },
  {
    name: "Microsoft Edge",
    vendor: "Microsoft",
    winget_id: "Microsoft.Edge",
    category: "Browser",
    homepage_url: "https://www.microsoft.com/edge",
    source_name: "Microsoft Edge Release Notes",
    source_type: "vendor_html",
    metadata: {
      url: "https://learn.microsoft.com/deployedge/microsoft-edge-relnote-stable-channel",
      versionPattern: "Version ([0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+)",
      releaseUrl: "https://learn.microsoft.com/deployedge/microsoft-edge-relnote-stable-channel",
      downloadUrl: "https://www.microsoft.com/edge/business/download",
    },
  },
  {
    name: "Visual Studio Code",
    vendor: "Microsoft",
    winget_id: "Microsoft.VisualStudioCode",
    category: "Developer Tool",
    homepage_url: "https://code.visualstudio.com/",
    source_name: "VS Code Stable API",
    source_type: "vendor_json",
    metadata: {
      url: "https://update.code.visualstudio.com/api/releases/stable",
      arrayIndex: 0,
      releaseUrl: "https://code.visualstudio.com/updates",
      downloadUrl: "https://code.visualstudio.com/download",
    },
  },
  {
    name: "Node.js LTS",
    vendor: "OpenJS Foundation",
    winget_id: "OpenJS.NodeJS.LTS",
    category: "Runtime",
    homepage_url: "https://nodejs.org/",
    source_name: "Node.js Release Index",
    source_type: "vendor_json",
    metadata: {
      url: "https://nodejs.org/dist/index.json",
      arrayFind: { lts: true },
      fallbackArrayIndex: 0,
      versionPath: "version",
      stripPrefix: "v",
      releaseUrl: "https://nodejs.org/en/about/previous-releases",
      downloadUrl: "https://nodejs.org/en/download",
    },
  },
  {
    name: "Git for Windows",
    vendor: "Git",
    winget_id: "Git.Git",
    category: "Developer Tool",
    homepage_url: "https://gitforwindows.org/",
    source_name: "GitHub Releases",
    source_type: "github_release",
    metadata: {
      owner: "git-for-windows",
      repo: "git",
      downloadUrl: "https://git-scm.com/download/win",
    },
  },
  {
    name: "GitHub Desktop",
    vendor: "GitHub",
    winget_id: "GitHub.GitHubDesktop",
    category: "Developer Tool",
    homepage_url: "https://desktop.github.com/",
    source_name: "GitHub Releases",
    source_type: "github_release",
    metadata: {
      owner: "desktop",
      repo: "desktop",
      downloadUrl: "https://desktop.github.com/",
    },
  },
  {
    name: "7-Zip",
    vendor: "Igor Pavlov",
    winget_id: "7zip.7zip",
    category: "Compression",
    homepage_url: "https://www.7-zip.org/",
    source_name: "7-Zip Download Page",
    source_type: "vendor_html",
    metadata: {
      url: "https://www.7-zip.org/download.html",
      versionPattern: "Download 7-Zip ([0-9.]+)",
      releaseUrl: "https://www.7-zip.org/download.html",
      downloadUrl: "https://www.7-zip.org/download.html",
    },
  },
  {
    name: "Notepad++",
    vendor: "Notepad++",
    winget_id: "Notepad++.Notepad++",
    category: "Editor",
    homepage_url: "https://notepad-plus-plus.org/",
    source_name: "GitHub Releases",
    source_type: "github_release",
    metadata: {
      owner: "notepad-plus-plus",
      repo: "notepad-plus-plus",
      downloadUrl: "https://notepad-plus-plus.org/downloads/",
    },
  },
  {
    name: "ShareX",
    vendor: "ShareX",
    winget_id: "ShareX.ShareX",
    category: "Utility",
    homepage_url: "https://getsharex.com/",
    source_name: "GitHub Releases",
    source_type: "github_release",
    metadata: {
      owner: "ShareX",
      repo: "ShareX",
      downloadUrl: "https://getsharex.com/downloads/",
    },
  },
  {
    name: "Zoom",
    vendor: "Zoom",
    winget_id: "Zoom.Zoom",
    category: "Communication",
    homepage_url: "https://zoom.us/",
    source_name: "Zoom Download Page",
    source_type: "vendor_html",
    metadata: {
      url: "https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0060716",
      versionPattern: "Version ([0-9]+\\.[0-9]+\\.[0-9]+)",
      releaseUrl: "https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0060716",
      downloadUrl: "https://zoom.us/download",
    },
  },
  {
    name: "Slack",
    vendor: "Slack",
    winget_id: "SlackTechnologies.Slack",
    category: "Communication",
    homepage_url: "https://slack.com/",
    source_name: "Slack Releases",
    source_type: "vendor_html",
    metadata: {
      url: "https://slack.com/release-notes/windows",
      versionPattern: "Slack ([0-9]+\\.[0-9]+\\.[0-9]+)",
      releaseUrl: "https://slack.com/release-notes/windows",
      downloadUrl: "https://slack.com/downloads/windows",
    },
  },
  {
    name: "Microsoft Teams",
    vendor: "Microsoft",
    winget_id: "Microsoft.Teams",
    category: "Communication",
    homepage_url: "https://www.microsoft.com/microsoft-teams/",
    source_name: "Teams Download Page",
    source_type: "vendor_html",
    metadata: {
      url: "https://learn.microsoft.com/microsoftteams/new-teams-bulk-install-client",
      versionPattern: "([0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+)",
      releaseUrl: "https://learn.microsoft.com/microsoftteams/new-teams-whats-changing",
      downloadUrl: "https://www.microsoft.com/microsoft-teams/download-app",
    },
  },
  {
    name: "VLC media player",
    vendor: "VideoLAN",
    winget_id: "VideoLAN.VLC",
    category: "Media",
    homepage_url: "https://www.videolan.org/vlc/",
    source_name: "VLC Download Page",
    source_type: "vendor_html",
    metadata: {
      url: "https://www.videolan.org/vlc/",
      versionPattern: "VLC ([0-9]+\\.[0-9]+\\.[0-9]+)",
      releaseUrl: "https://www.videolan.org/vlc/releases/",
      downloadUrl: "https://www.videolan.org/vlc/download-windows.html",
    },
  },
  {
    name: "FileZilla",
    vendor: "FileZilla",
    winget_id: "FileZilla.FileZilla",
    category: "File Transfer",
    homepage_url: "https://filezilla-project.org/",
    source_name: "FileZilla Website",
    source_type: "vendor_html",
    metadata: {
      url: "https://filezilla-project.org/",
      versionPattern: "FileZilla Client ([0-9]+\\.[0-9]+\\.[0-9]+)",
      releaseUrl: "https://filezilla-project.org/versions.php",
      downloadUrl: "https://filezilla-project.org/download.php",
    },
  },
  {
    name: "WinSCP",
    vendor: "WinSCP",
    winget_id: "WinSCP.WinSCP",
    category: "File Transfer",
    homepage_url: "https://winscp.net/",
    source_name: "WinSCP Website",
    source_type: "vendor_html",
    metadata: {
      url: "https://winscp.net/eng/download.php",
      versionPattern: "WinSCP ([0-9]+\\.[0-9]+\\.[0-9]+)",
      releaseUrl: "https://winscp.net/eng/docs/history",
      downloadUrl: "https://winscp.net/eng/download.php",
    },
  },
  {
    name: "PuTTY",
    vendor: "Simon Tatham",
    winget_id: "PuTTY.PuTTY",
    category: "Remote Access",
    homepage_url: "https://www.chiark.greenend.org.uk/~sgtatham/putty/",
    source_name: "PuTTY Latest Page",
    source_type: "vendor_html",
    metadata: {
      url: "https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html",
      versionPattern: "PuTTY ([0-9]+\\.[0-9]+)",
      releaseUrl: "https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html",
      downloadUrl: "https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html",
    },
  },
  {
    name: "Python",
    vendor: "Python Software Foundation",
    winget_id: "Python.Python.3.13",
    category: "Runtime",
    homepage_url: "https://www.python.org/",
    source_name: "Python Downloads Page",
    source_type: "vendor_html",
    metadata: {
      url: "https://www.python.org/downloads/windows/",
      versionPattern: "Python ([0-9]+\\.[0-9]+\\.[0-9]+)",
      releaseUrl: "https://www.python.org/downloads/",
      downloadUrl: "https://www.python.org/downloads/windows/",
    },
  },
  {
    name: "Docker Desktop",
    vendor: "Docker",
    winget_id: "Docker.DockerDesktop",
    category: "Developer Tool",
    homepage_url: "https://www.docker.com/products/docker-desktop/",
    source_name: "Docker Desktop Release Notes",
    source_type: "vendor_html",
    metadata: {
      url: "https://docs.docker.com/desktop/release-notes/",
      versionPattern: "Docker Desktop ([0-9]+\\.[0-9]+\\.[0-9]+)",
      releaseUrl: "https://docs.docker.com/desktop/release-notes/",
      downloadUrl: "https://www.docker.com/products/docker-desktop/",
    },
  },
  {
    name: "PowerToys",
    vendor: "Microsoft",
    winget_id: "Microsoft.PowerToys",
    category: "Utility",
    homepage_url: "https://learn.microsoft.com/windows/powertoys/",
    source_name: "GitHub Releases",
    source_type: "github_release",
    metadata: {
      owner: "microsoft",
      repo: "PowerToys",
      downloadUrl: "https://github.com/microsoft/PowerToys/releases/latest",
    },
  },
  {
    name: "Bitwarden",
    vendor: "Bitwarden",
    winget_id: "Bitwarden.Bitwarden",
    category: "Password Manager",
    homepage_url: "https://bitwarden.com/",
    source_name: "GitHub Releases",
    source_type: "github_release",
    metadata: {
      owner: "bitwarden",
      repo: "clients",
      downloadUrl: "https://bitwarden.com/download/",
    },
  },
  {
    name: "KeePassXC",
    vendor: "KeePassXC",
    winget_id: "KeePassXCTeam.KeePassXC",
    category: "Password Manager",
    homepage_url: "https://keepassxc.org/",
    source_name: "GitHub Releases",
    source_type: "github_release",
    metadata: {
      owner: "keepassxreboot",
      repo: "keepassxc",
      downloadUrl: "https://keepassxc.org/download/",
    },
  },
  {
    name: "Tailscale",
    vendor: "Tailscale",
    winget_id: "tailscale.tailscale",
    category: "VPN",
    homepage_url: "https://tailscale.com/",
    source_name: "GitHub Releases",
    source_type: "github_release",
    metadata: {
      owner: "tailscale",
      repo: "tailscale",
      downloadUrl: "https://tailscale.com/download",
    },
  },
  {
    name: "RustDesk",
    vendor: "RustDesk",
    winget_id: "RustDesk.RustDesk",
    category: "Remote Access",
    homepage_url: "https://rustdesk.com/",
    source_name: "GitHub Releases",
    source_type: "github_release",
    metadata: {
      owner: "rustdesk",
      repo: "rustdesk",
      downloadUrl: "https://rustdesk.com/",
    },
  },
  {
    name: "LibreOffice",
    vendor: "The Document Foundation",
    winget_id: "TheDocumentFoundation.LibreOffice",
    category: "Office",
    homepage_url: "https://www.libreoffice.org/",
    source_name: "LibreOffice Download Page",
    source_type: "vendor_html",
    metadata: {
      url: "https://www.libreoffice.org/download/download-libreoffice/",
      versionPattern: "LibreOffice ([0-9]+\\.[0-9]+\\.[0-9]+)",
      releaseUrl: "https://www.libreoffice.org/download/release-notes/",
      downloadUrl: "https://www.libreoffice.org/download/download-libreoffice/",
    },
  },
];